name: 'Upstream to PR'
description: 'Fetch upstream branch and open PR (if any changes)'
author: 'Filipe Pina'
inputs:
  token:
    description: 'github token used to create the pull request'
    required: true
  upstream-repository:
    description: 'git/http URL for the upstream project'
    required: true
  upstream-branch:
    description: 'upstream branch of the upstream project to monitor'
    required: true
    default: main
  upstream-tag:
    description: 'upstream tag expression of the upstream project to monitor - using this ignores upstream-branch'
    required: false
  keep-old:
    description: 'delete older PRs (and branches) when a more recent PR is open'
    default: false

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'refresh-ccw'
  color: 'blue'
